apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-claim
  namespace: todo-space
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.08Gi
