apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-claim
  namespace: main-space
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.08Gi
