apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: main-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      volumes: # Define volume
        - name: shared-vol
          emptyDir: {}
      containers:
        - name: time-generator
          image: aldahdouh/time-generator
          volumeMounts: # Mount volume
          - name: shared-vol
            mountPath: /app
        - name: hash-generator
          image: aldahdouh/hash-generator
          volumeMounts: # Mount volume
          - name: shared-vol
            mountPath: /app
          env:
            - name: MESSAGE 
              valueFrom:
                configMapKeyRef:
                  name: main-app-configmap           # The ConfigMap this value comes from.
                  key: MESSAGE # The key to fetch.
          