apiVersion: v1
kind: Service
metadata:
  name: ingress-postgres-srv
  namespace: main-space
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: ingress-postgres-srv
  clusterIP: None
  selector:
    app: postgres