apiVersion: v1
kind: Service
metadata:
  name: ingress-pingpong-app-srv
  namespace: main-space
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - port: 2343
      protocol: TCP
      targetPort: 3001
