apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: main-space
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: ingress-postgres-srv
  replicas: 1 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
                name: postgres-keys
                key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
                name: postgres-keys
                key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
                name: postgres-keys
                key: POSTGRES_USER
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/PostgreSQL/data
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 100Mi